### ISSUE TITLE
Error reporting: Compling ISSM with python triggers running error under python

### ISSUE THREAD

**Issue by inwoo-park** [ISSMteam/ISSM#17]
Hi, developers.

I usually use ISSM with both MATLAB and Python. However, my old machine triggers the error following error when using ISSM with python:

```bash
  File "/home/inwoo/issm/ISSM/src/m/modules/IssmConfig.py", line 1, in <module>
    from IssmConfig_python import IssmConfig_python
ImportError: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/DATA/externalpackages/matlab/install/bin/glnxa64/libMatlabDataArray.so)
```

My machine uses the `gcc` version 4.8.5 and does not contain the `CXXABI_1.3.8`. It seems that `gcc>=5` is required to resolve this issue. However, I cannot upgrade the machine because this machine is a `cluster`. If I upgrade the gcc version, I am concerned that it might distrub pre-installed packages. Furthermore, since this machine operates in offline mode (not allowed to conncet to the network), downloading the latest gcc vesion is challenging. 

* `CXXABI` in `libstdc++.so.6`
```bash
$ strings /usr/lib64/libstdc++.so.6 | grep CXXABI
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
CXXABI_TM_1
```

Now, I have found a solution to resolve this problem.
While compiling the ISSM with Python, `src/wrappers/python/Makefile.am` file contains the `$(MEXLIB)` flag on **_line 154_** (maybe..).

[Previous in `src/wrappers/python/Makefile.am` line 154 (maybe)]
```bash
libISSMApi_la_LIBADD = ... $(MEXLIB)
```
[Recommended in `src/wrappers/python/Makefile.am` line 154 (maybe)]

```bash
libISSMApi_la_LIBADD = ... # remove $(MEXLIB)
```

However, it seems that when using ISSM with Python under compiling for both Python and MATLAB does not require `$(MEXLIB)`. When I remove using `$MEXLIB` from this line, ISSM works well with Python.

Should we remove the `$(MEXLIB)` in `src/wrappers/python/Makefile.am`?

Best regards,
Inwoo

**Comment by MathieuMorlighem** [comment]
Good catch Inwoo! Yes please remove it, this looks like a bug

**Comment by TidbitSoftware** [comment]
Hi guys, I totally missed this issue being filed and this one was definitely my fault. Should have been more careful when consolidating the wrapper Makefile.am's. I'll sort out now how to get notifications for all issues.
